### ISSUE TITLE
UndefVarError: `generate_ray` not defined

### ISSUE THREAD

**Issue by aplavin** [dominic-chang/Krang.jl#21]
Trying out Krang as part of https://github.com/openjournals/joss-reviews/issues/7273, and noticed that the slow light example (https://dominic-chang.com/Krang.jl/dev/examples/mino_time_example) doesn't work: throws `UndefVarError: generate_ray not defined` as `Krang.generate_ray` doesn't seem to exist.

**Comment by dominic-chang** [comment]
Should be fixed in c16d1079d5e7d40d8507ff781b4b307cba9fb08c
