### ISSUE TITLE
difficulty with GPU examples

### ISSUE THREAD

**Issue by ExpandingMan** [dominic-chang/Krang.jl#24]
I'm still having quite a bit of trouble adapting the provided examples, in this case `coordinate-example.jl` to work with CUDA.

May I suggest the following: set up a complete working example that you have verified works properly, exactly as-is with whatever GPU you have access to, and then I will go and do whatever is needed to make sure it also works with CUDA?

**Comment by dominic-chang** [comment]
What version of the docs are you using?

**Comment by ExpandingMan** [comment]
Specifically what I just did is try to run `coordinate-example.jl` from latest `main` by swapping out `rendered_scene` with the provided CUDA version.  Again, I really think a complete working as-is example would make things much easier.  Something even more minimal than `coordinate-example.jl` would be fine, I just want to be absolutely sure it's supposed to work on GPU in the first place before I try to get it working with CUDA.

**Comment by dominic-chang** [comment]
Ah, yeah I see. There's a typo in the docs, it should be

`Array(coordinate_point.(CuArray(camera.screen.pixels), Ref(geometry))`

not just

`coordinate_point.(CuArray(camera.screen.pixels), Ref(geometry)`

since I have to take it off the GPU to plot.

Were you having an indexing error? Here's a version of the `draw` function that worked with Metal on my mac

```
# Draw Function
# This function draws the coordinates associated with the n=0,1,2 subimages of a cone with opening angle θs.
function draw!(axes_list, camera, coordinates, rmin, rmax, θs)
    times, radii, azimuths = coordinates 
    map(axes -> empty!.(axes), axes_list)

    geometries = (Krang.ConeGeometry(θs, (i, rmin, rmax)) for i in 0:2)
    
    for (i, geometry) in enumerate(geometries)
        rendered_scene = Array(coordinate_point.(MtlArray(camera.screen.pixels), Ref(geometry)))
        for I in CartesianIndices(rendered_scene)
            times[I] = rendered_scene[I][1]
            radii[I] = rendered_scene[I][2]
            azimuths[I] = rendered_scene[I][4]
        end
        coordinates = (times, radii, mod2pi.(azimuths ))
        for j in 1:3
            heatmap!(axes_list[i][j], coordinates[j], colormap = colormaps[j], colorrange=colorrange[j])
        end
    end
end
```
I think replacing the `MtlArray` with `CuArray` should do the trick. I would also try the main branch. There was a small typo that was causing a type instability whose fix I just pushed.

**Comment by ExpandingMan** [comment]
Could you please, please add a full and explicit example, even a very minimal one, that definitely works with GPU exactly as is?  I don't even care if it's in the docs, and I will gladly do whatever is required to make sure it works for me swapping out whatever you use with CUDA, but I've done quite a lot of juggling these examples trying to adapt them and I just want to firmly ground in a common frame of reference.

**Comment by dominic-chang** [comment]
Sorry, I'm really not sure why I wasn't understanding that you were asking me to add examples. I think I must be sleep deprived 😅

Here's some example scripts that run on my GPU. I think they should run if you just replace the `MtlArray` with `CuArray`.
Please use the main branch for now. I'll push a new patch in a bit.

https://github.com/dominic-chang/Krang.jl/tree/main/gpu_examples

**Comment by dominic-chang** [comment]
I pushed a new patch. The GPU examples aren't in the documentation itself, but they are available as scripts in the /gpu_examples folder as previously mentioned. Let me know if there are any issues. There are sometimes rendering artifacts with `Float32` so I would use `Float64` if you can. The rendering issues, I'm pretty sure, are due to incompatible convergence criteria in some of the routines I'm using. Here's an example where the rays develop spikes at some locations.

## Float64: 

<img width="392" alt="image" src="https://github.com/user-attachments/assets/94a4aacc-62cf-4866-9eb5-8ec9a97f57c7">

## Float32:

<img width="432" alt="image" src="https://github.com/user-attachments/assets/0e51b1da-22f3-4183-b4e7-325e873e9085">

**Comment by ExpandingMan** [comment]
So, unfortunately the GPU compiler seems to very easily go type unstable for a lot of this stuff, even though it's all perfectly stable on CPU.  It looks like all the tuple return types are making it shit itself.  Based on my experience, *maybe* things would be better if there were more dedicated structs for holding a lot of the return values? But who knows.

Regardless, it's now looking to me like, although some stuff works, it would take someone with an nvidia card a significant effort to go through and get it working with CUDA.  That's unfortunate but it's not the fault of this package.  Definitely would not make sense for that to hold up the JOSS review, in my mind that's done and I'll go to the issue and check my list and sign off now.

As for the floating point stuff, if there's any low-hanging fruit of stuff you can make more robust in obvious ways, by all means go for it, but floating point is just one of those facts of life that we all have to deal with and you will not be able to rescue users from its fundamental limitations, so I think this is fine.  If there's any algorithms that you think are particularly dangerous or safe with `Float32`, might be nice to point it out in the docs, but it's certainly not your job to explain floating point to users so I wouldn't be worried about it.

**Comment by ExpandingMan** [comment]
I am closing this.  The examples that are currently there are good, CUDA is a bunch of separate issues that should be more specific, so people can open those as needed.

**Comment by dominic-chang** [comment]
Thanks for that. I'm surprised you're having so many issues with CUDA. Did the GPU examples fail when you tried them, or are you having issue with other functions?

**Comment by ExpandingMan** [comment]
Naively it fails with inscrutable errors, but as I dug into it I realized that it was type unstable and that was causing the failures.  Again, I see this as "GPU's are a pain in the ass", there are undoubtedly things that can be done to get it working, but it's not because this package is doing anything bad or unusual, it's just that CUDA is too fragile.

It's looking to me like most of the instability is happening around the `Tuple` returns from many of the functions in this package.  Why those are so fragile I do not know.

Most of the code in this package looks to me entirely appropriate for GPU (no heap allocs, type stable on CPU at least) so I don't think there are any glaring fundamental issues, it would just take someone to go through the pain of getting it to work.  It's doable, so I don't think it's a big deal that CUDA doesn't work in the current state.
